---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-buyer
  labels:
    app: chaincode-basic-buyer
spec:
  selector:
    matchLabels:
      app: chaincode-basic-buyer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-buyer
    spec:
      containers:
        - image: quanglathe/basic-chaincode-hlf:1.0
          imagePullPolicy: Always
          name: chaincode-basic-buyer
          env:
            - name: CHAINCODE_ID
              value: 'basic:ce079999488ee6eb2260c834178511a54b188d02221c18e164d15e233c90e431'
            - name: CHAINCODE_SERVER_ADDRESS
              value: '0.0.0.0:7052'
          ports:
            - containerPort: 7052
