---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-seller
  labels:
    app: chaincode-basic-seller
spec:
  selector:
    matchLabels:
      app: chaincode-basic-seller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-seller
    spec:
      containers:
        - image: quanglathe/basic-chaincode-hlf:1.0
          imagePullPolicy: Always
          name: chaincode-basic-seller
          env:
            - name: CHAINCODE_ID
              value: 'basic:1db5c1b60335071dbac610cddf935dc96de318ce6f3d65729c06d5503d924980'
            - name: CHAINCODE_SERVER_ADDRESS
              value: '0.0.0.0:7052'
          ports:
            - containerPort: 7052
