apiVersion: v1
kind: Service
metadata:
  name: ca-buyer
  labels:
    app: ca-buyer
spec:
  type: ClusterIP
  selector:
    app: ca-buyer
  ports:
    - protocol: TCP
      targetPort: 8054
      port: 8054
