apiVersion: v1
kind: Service
metadata:
  name: ca-seller
  labels:
    app: ca-seller
spec:
  type: ClusterIP
  selector:
    app: ca-seller
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054
