apiVersion: v1
kind: Pod
metadata:
  name: agm-pv-pod
  labels:
    app: task-pv
spec:
  containers:
    - name: task-pv-container
      image: nginx
      resources:
        requests:
          memory: '64Mi'
          cpu: '150m'
        limits:
          memory: '128Mi'
          cpu: '250m'
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: agmpvc
