apiVersion: v1
kind: PersistentVolume
metadata:
  name: agmpv
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/v1'
